version: '3.4'

services:
  elasticsearch:
    container_name: es-container-vi
    image: thaichihien/elasticsearch-analysis-vietnamese:8.7.0
    restart: on-failure
    ports:
      - "9200:9200"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        hard: -1
        soft: -1
    environment:
      ES_JAVA_OPTS: "-Xmx2g -Xms2g"
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "changeme"
      bootstrap.memory_lock: "true"
      discovery.type: "single-node"
      xpack.security.enabled: "false"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    networks:
      - mirco
  rabbitmq:
    container_name: rabbit-container
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mirco
  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - mirco
  

networks:
  mirco:
    driver: bridge

volumes:
  esdata:
  redis:
    driver: local